app_todoLst/urls.py
from django.urls import path,include

from . import views


app_name='todoLst'
urlpatterns = [
    path('', views.index),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('log_out/', views.log_out, name='log_out'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in_process/', views.sign_in_process, name='sign_in_process'),
    path('sign_un_process/', views.sign_up_process, name='sign_up_process'),
    path('tasks/', views.tasks, name='tasks' ),

]
    







	

site_todoList/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('', include('app_todoLst.urls')),
    path('admin/', admin.site.urls),
]

app_todoLst/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Task(models.Model):

	#priority_cats=[ (0,'low'),(1,'medium'),(2,'high')  ]
	#status_cats=[ (0,'waiting'),(1,'in_progress'),(2,'done')  ]

	task_text=models.CharField(max_length=300)
	priority=models.IntegerField()
	status=models.IntegerField()
	user=models.ForeignKey(User, on_delete=models.CASCADE)


		

app_todoLst/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate
from math import ceil
from .models import Task
# Create your views here.
"""
def preauth(request):
	return render(request,'todoLst/auth_template.html')

def auth(request):
	print(request.POST)
	return HttpResponseRedirect(reverse( 'todoLst:tt') )
	
def tt(request):
	print(request.POST)
	return HttpResponse('testing')

"""		

fields=['priority','status']
allFields=['task_text']+fields


fieldInfo={ 'status':['waiting','in_progress','done'],
		 'priority': ['low','medium','high']}



pgSize_dflt=10


def index(request):
	if 'signed' in request.session:
		return HttpResponseRedirect( reverse('todoLst:tasks'))
	else:
		return HttpResponseRedirect( reverse('todoLst:sign_in'))
def sign_in(request):
	TasksState.clearSession(request.session)


	return render(request, 'todoLst/sign_in_template.html')


def sign_in_process(request):



	#print('running here',request.POST['auth_action'])
	request.session['lgn']=request.POST['lgn']
	request.session['pwd']=request.POST['pwd']

	

	if request.POST['auth_action']=='sign up':
		return HttpResponseRedirect( reverse('todoLst:sign_up'))
	else:
		
		return HttpResponseRedirect( reverse('todoLst:tasks'))


def log_out(request):
	AuthState.clearSession(request.session)
	return HttpResponseRedirect( reverse('todoLst:sign_in'))

def sign_up(request):
	TasksState.clearSession(request.session)

	return render(request, 'todoLst/sign_up_template.html')


def sign_up_process(request):
	request.session['lgn']=request.POST['lgn']
	request.session['pwd']=request.POST['pwd']	





	if len(request.POST['lgn'])==0 or len(request.POST['pwd'])==0 or len(request.POST['pwd2'])==0:
		return HttpResponse('all fields nust be filled')
	if request.POST['pwd2']!=request.POST['pwd']:
		return HttpResponse('passwords are different!')

	login=request.POST['lgn']
	try:					
		User.objects.get(username=login)
		return HttpResponse('user with such login already exists')
	
	except 	ObjectDoesNotExist:
		pass
	
	User.objects.create_user(request.session['lgn'], '', request.session['pwd'])


	return HttpResponseRedirect( reverse('todoLst:tasks'))







def onAuthProblem():
	return HttpResponseRedirect( reverse('todoLst:sign_in'))




class AuthState:
	def __init__(self,session):
		self.lgn=( session['lgn'] if 'lgn' in session else None  )
		self.pwd=( session['pwd'] if 'pwd' in session else None  )
	def looksAuthd(self):
		return None not in (self.lgn,self.pwd)

	@staticmethod	
	def clearSession(session):
		for field in ['lgn','pwd']:
			if field in session:
				del(session[field])



def getOrAlt(obj,key,alt=None):

	return (obj[key] if key in obj else alt)


class TasksState:
	"""
	extracts task representation/update cofiguration from request.session and request.post
	+
	save representation configurarion into requset.session
	####################
	representation configuraion:

	pgN - page number to show
	pgSize - tasks per page
	filterState - current task filter setting
	
	update configuration:

        update_type - specifies what kind of change if any should be applied to stored task		
	newTaskInfo - dictionary with all fields to create new task
	selected_ids - list of seleted ids
	taskUpdateDict - information on how to update selected tasks
	warning - list of warnings that contains description of problems encountered
	(not all update configuration elements presented in every instance)		
	
	

	"""
				
	repFields=['pgN','pgSize','filterState']
	def __init__(self,session, post):
		dfltFieldVals_rep={'pgN':1,'pgSize':pgSize_dflt,'filterState':{}}
		self.warnings=[]	
	
		for field in dfltFieldVals_rep:
			self.__dict__[field]=getOrAlt(session,field,dfltFieldVals_rep[field])

		self.update_type=getOrAlt(post,'update_type','just show' )

		self.selected_ids=(post.getlist('selected_ids') if  'selected_ids' in post else [] )

		


		if self.update_type=='add task':
			newTaskInfo={}
			for field in allFields:
				if field+'__new' not in post:
					self.update_type=='just show'			
					self.warnings.append(" new task can't be created: {} must be specified".format(field))
					newTaskInfo=None
					break
				else:
					newTaskInfo[field]=post[field+'__new']
			self.newTaskInfo=newTaskInfo
			
			self.pgN=1
			
		
		elif self.update_type=='update selected':
			self.taskUpdateDict={}
			for id in self.selected_ids:
				self.taskUpdateDict[id]={}
				for field in allFields:
					if field+'__'+id in post:
						self.taskUpdateDict[id][field]=post[field+'__'+id]

			self.pgN=1

		elif self.update_type=='apply filters':
			self.filterState={}
			for field in fields:
				if field+'__filter' in post:
					self.filterState[field]=post.getlist(field+'__filter')

			self.pgN=1

		elif self.update_type=='go to':
			try:
				self.pgN=int(post['pgN'])
			except Exception:
				self.pgN=1
		elif self.update_type=='Set page size to':
			try:
				self.pgSize=int(post['pgSize'])
				self.pgN=1
			except Exception:
				self.pgSize=pgSize_dflt		
		



		for field in dfltFieldVals_rep:
			session[field]=self.__dict__[field]

		 
		
		
				
	def getFilter(self):
		return {field+'__in':self.filterState[field] for field in self.filterState  }					
			
				
	@staticmethod	
	def clearSession(session):
		for field in TasksState.repFields:
			if field in session:
				del(session[field])
		
						
		


	
def tasks(request):
	authState=AuthState(request.session)
	tasksState=TasksState(request.session,request.POST)

	print(tasksState.__dict__)
	print(request.POST)

	if not authState.looksAuthd():	
		return onAuthProblem()

	
	user = authenticate(username=authState.lgn, password=authState.pwd)

	if user is None:	
		return onAuthProblem()
	else:
		
		
		if tasksState.update_type=='delete selected':
			removeTasks( tasksState.selected_ids ,user )

		elif tasksState.update_type=='update selected':
			updateTasks( tasksState.taskUpdateDict,user  )

		elif tasksState.update_type=='add task':
			addTask( tasksState.newTaskInfo,user )

			
			

		if user.is_superuser:
			tasks=Task.objects.filter(**tasksState.getFilter()).order_by('-pk')
		else:
			tasks=user.task_set.filter(**tasksState.getFilter()).order_by('-pk')
		
		#taskN=len(tasks)
		pgSize=max(1,tasksState.pgSize)
		maxPgN= max(int(ceil(len(tasks)/ pgSize )),1)
		pgN=min(max( 1, tasksState.pgN  ),maxPgN)
			
		return render(request,'todoLst/tasks_template.html', 
			dict( user=user,isAdmin=user.is_superuser,tasks=tasks[(pgN-1)*pgSize:pgN*pgSize],
				fields=fields,fieldInfo=fieldInfo, filterConf=tasksState.filterState,  pages=list(range(1,maxPgN+1)), pgN=pgN, warnings=tasksState.warnings  )   )				
		
	









	

def removeTasks(pks,user):
	if user.is_superuser:
		Task.objects.filter( pk__in=pks ).delete()
	else:
		Task.objects.filter( pk__in=pks, user__username=user.username ).delete()	
def updateTasks(taskDict,user):
	def updateTask(task):
		for field in allFields:
			if field in taskDict[str(task.pk)]:
			
				task.__dict__[field]=taskDict[str(task.pk)][field]
			task.save()
	if user.is_superuser:
		for task in Task.objects.filter( pk__in=list(taskDict) ):
			updateTask(task)

	else:
		for task in user.task_set.filter( pk__in=list(taskDict) ):
			updateTask(task)


def addTask(taskSpecsDict,user):
	if taskSpecsDict:
		user.task_set.create(**taskSpecsDict )

app_todoLst/templates/todoLst/auth_template.html
<form action="{% url 'todoLst:auth' %}" method="post">
{% csrf_token %}

Login:<input name='lgn' type="text" > </input><br>
Password:<input name='pwd' type="password"><br>
<input type="submit" name='auth_action' value="sign in"><input type="submit" name='auth_action' value="sign up">
</form>

app_todoLst/templates/todoLst/selectList.html
{%load my_filters%}

<select onchange="highlightChanges(this)" name="{{ name|add:'__'|add:pk }}" data-value0="{{opnStd}}">	
    {% for opn in opnLst %}
    <option {%if opnStd == forloop.counter|add:'-1' %} selected {%endif%} value= "{{ forloop.counter|add:'-1' }}"  >{{opn}}</option>
    {% endfor %}
</select>

app_todoLst/templates/todoLst/sign_in_template.html
<form action="{% url 'todoLst:sign_in_process' %}" method="post">
{% csrf_token %}

Login:<input name='lgn' type="text" > </input><br>
Password:<input name='pwd' type="password"><br>
<input type="submit" name='auth_action' value="sign in"><input type="submit" name='auth_action' value="sign up">
</form>

app_todoLst/templates/todoLst/sign_template.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'todoLst:addUser' %}" method="post">
{% csrf_token %}

Login:<input name='lgn' type="text" > </input><br>
Password:<input name='pwd' type="password"><br>
Repeat Password:<input name='pwd2' type="password"><br>
<input type="submit" value="sign up">
</form>

app_todoLst/templates/todoLst/sign_up_template.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'todoLst:sign_up_process' %}" method="post">
{% csrf_token %}

Login:<input name='lgn' type="text" > </input><br>
Password:<input name='pwd' type="password"><br>
Repeat Password:<input name='pwd2' type="password"><br>
<input type="submit" value="sign up">
</form>

app_todoLst/templates/todoLst/tasks_template.html
{%load my_filters%}



{% if warnings %}
************warning************
<br>
{% for warning in warnings %}
{{warning}}
<br>
{%endfor%}

*******************************
{% endif %}

<script>
function highlightChanges(el){
 if (el.value!=el.getAttribute('data-value0')) {el.style.color='red'} else {el.style.color=''} 
 }

function inpOn(el){



	var newEl = document.createElement('textarea');

	//newEl.type = 'text';

        newEl.name = 'task_text__'+el.id;

	newEl.innerHTML = el.innerHTML;


	el.parentNode.replaceChild(newEl, el);

}

function inpOff(el){
 if (el.value!=el.getAttribute('data-value0')) {el.style.color='red'} else {el.style.color=''} 
 }

</script>

<form action="{% url 'todoLst:tasks' %}" method="post">
{% csrf_token %}
{% if tasks %}
<h3> Tasks available for <i>{{user.username}}</i>: </h3>




<p>Pages: 
{% for page in pages %}
<label onclick="document.getElementById('goto_input').value='{{page}}'" for="goto_btn"  > 
{%if page == pgN %}
<strong>{{page}} </strong>
{% else %}
{{page}}
{% endif %}

</label>; 

{%endfor%}
<input id="goto_btn" type="submit" name='update_type' value="go to"> <input id="goto_input" type="number" style="width:80" name="pgN" />
<br>
<input type="submit" name="update_type" value="Set page size to"> <input type="number" style="width:80" name="pgSize" />
</p> 


<table>
<tr><th></th>
<th>Task Description</th>
<th>Priority</th>
<th>Status</th>
{%if isAdmin%}<th> Owner</th> {%endif%}</tr> 

{% for task in tasks %}

    <tr><td><input type="checkbox" value="{{task.pk}}" name="selected_ids"> </td>
        <td><p id="{{task.id}}" ondblclick="inpOn(this)">{{task.task_text }} </p></td>
	
	{%for field in fields  %}
	<td> {% include "todoLst/selectList.html" with opnLst=fieldInfo|loc:field opnStd=task|getAttr:field name=field pk=task.pk|stringformat:'i' %} </td>
	{%endfor%}

	{%if isAdmin%}<td> {{task.user.username}}</td> {%endif%}</tr>     
{% endfor %}
</table>


<br>
<input type="submit" name='update_type' value="delete selected">
<input type="submit" name='update_type' value="update selected">
{%else%}
<h3> No tasks are available for <i>{{user.username}}</i> that match current filter: </h3>
{%endif%}

<br>
#################################################
<h3> Filtering: </h3>

{% csrf_token %}


{% for field in fields %}
<p>Task {{field}}:</p>
{% for option in  fieldInfo|loc:field %}

    <input  type="checkbox" name="{{field|add:'__filter'}}" id="{{option|add:'__filter'}}" value="{{forloop.counter|add:'-1' }}"  {% if forloop.counter|add:'-1'|stringformat:'i' in  filterConf|loc:field%} checked {%endif%} >
    <label for="{{field|add:'__filter'}}">{{ option }}</label>
{% endfor %}
<br>

{%endfor%}



<input type="submit" name="update_type" value="apply filters">

<br>
#################################################
<h3> Task creation form: </h3>

{% csrf_token %}



<p>Task Description:</p>
<textarea name='task_text__new' rows=5 cols=40></textarea><br>


{%for field in fields%}
<p>Task {{field}}:</p>
{% for option in fieldInfo|loc:field %}
    <input type="radio" name="{{field|add:'__new'}}" id="{{option|add:'__new'}}" value="{{forloop.counter|add:'-1' }}">
    <label for="{{option|add:'__new'}}">{{option}}</label>
{% endfor %}
<br>
{%endfor%}

<input type="submit" value="add task" name="update_type">

</form>
<br>
#################################################

<form action="{% url 'todoLst:log_out' %}">

<input type="submit" value="log out"> </input>

</form>
<br>
#################################################
<p id='demo' />

app_todoLst/templates/todoLst/tasks_template_new.html
{%load my_filters%}

<p> tasks available for user {{user.username}} </p>

<form action="{% url 'todoLst:rmvTask' %}" method="post">
{% csrf_token %}
<ul>
{% for task in tasks %}



	
    <li> <input type="checkbox" value="{{task.pk}}" name="to_del"> {{task.task_text }} -- {{ priorityList|loc:task.priority }} -- {{  statusList|loc:task.status }} </li>
    




{% endfor %}
</ul>
<input type="submit" value="delete selected">
</form>

<p> add more tasks </p>
<form action="{% url 'todoLst:addTask' %}" method="post">
{% csrf_token %}



<p>Task Description:<input name='task_text' type="text" > </input><br></p>


<p>Choose task priority:</p>
<select size="3" name="priority">

    {% for priority in priorityList %}
    <option value=" {{ forloop.counter|add:'-1' }}">{{priority}}</option>
    {% endfor %}
  </select>


<br>
<p>Task status:</p>
{% for status in statusList %}
    <input type="radio" name="status" id="{{status}}" value="{{ forloop.counter|add:'-1' }}">
    <label for="{{status }}">{{ status }}</label>
{% endfor %}
<br>
<input type="submit" value="add task">

</form>

app_todoLst/templates/todoLst/tasks_template_old.html
{%load my_filters%}


<h3> Tasks available for user <i>{{user.username}}</i>: </h3>

<form action="{% url 'todoLst:chngTasks' %}" method="post">
{% csrf_token %}
<ul>
{% for task in tasks %}

    <li> <input type="checkbox" value="{{task.pk}}" name="to_del"> 
        {{task.task_text }} 
	-- {% include "todoLst/selectList.html" with opnLst=priorityList opnStd=task.priority name='priority' pk=task.pk%} 
	-- {% include "todoLst/selectList.html" with opnLst=statusList opnStd=task.status name='status' pk=task.pk%}  
	{%if isAdmin%}-- {{task.user.username}} {%endif%}</li>     
{% endfor %}
</ul>
<input type="submit" name='update_type' value="delete selected">
<input type="submit" name='update_type' value="update selected">
</form>

#################################################
<h3> Filtering: </h3>
<form action="{% url 'todoLst:tasks' %}" method="post">
{% csrf_token %}

{%comment%}
<p>Order by:</p>
{% for field in fields  %}
<input type="radio" name="sort_by_field" id="{{field}}" value="{{field}}">
<label for="{{field}}">{{field}}</label>
{%endfor%}

<br>

<p>Order:</p>
{% for field in 'ascending descending'|split  %}


<input type="radio" name="sort_order" id="{{field}}" value="{{field}}">
<label for="{{field}}">{{field}}</label>



{%endfor%}


<br>
{%endcomment%}
<p>Task Priority:</p>
{% for priority in priorityList %}


    <input  type="checkbox" name="priority_filter" id="{{priority}}2" value="{{forloop.counter|add:'-1' }}"  {% if forloop.counter|add:'-1'|stringformat:'i' in  fltrs.priority%} checked {%endif%} >
    <label for="{{priority }}2">{{ priority }}</label>
{% endfor %}
<br>
<p>Task status:</p>
{% for status in statusList %}
    <input type="checkbox" name="status_filter" id="{{status}}2" value="{{ forloop.counter|add:'-1' }}" {% if forloop.counter|add:'-1'|stringformat:'i' in  fltrs.status%} checked {%endif%}>
    <label for="{{status }}2">{{ status }}</label>
{% endfor %}
<br>



<input type="submit" value="apply filters">
</form>

#################################################
<h3> Task creation form: </h3>
<form action="{% url 'todoLst:addTask' %}" method="post">
{% csrf_token %}



<p>Task Description:</p>
<textarea name='task_text' rows=5 cols=40></textarea><br>
<p>Task Priority:</p>
{% for priority in priorityList %}
    <input type="radio" name="priority" id="{{priority}}" value="{{forloop.counter|add:'-1' }}">
    <label for="{{priority }}">{{ priority }}</label>
{% endfor %}
<br>
<p>Task status:</p>
{% for status in statusList %}
    <input type="radio" name="status" id="{{status}}" value="{{ forloop.counter|add:'-1' }}">
    <label for="{{status }}">{{ status }}</label>
{% endfor %}
<br>
<input type="submit" value="add task">

</form>
###################################################

<form action="{% url 'todoLst:log_out' %}">

<input type="submit" value="log out"> </input>

</form>